# Importing necessary libraries

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import re
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("Players stats.csv")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0s
0,SR Tendulkar (IND),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20
1,V Kohli (IND),2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76,18
2,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
3,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,PR Reiffel (AUS),1992-1999,92,57,21,503,58,13.97,709,70.94,0,1,5
744,AR Nurse (WI),2016-2019,54,40,14,502,44,19.30,513,97.85,0,0,2
745,JE Emburey (ENG),1980-1993,61,45,10,501,34,14.31,664,75.45,0,0,3
746,Ghulam Shabber (UAE),2017-2019,23,23,0,500,90,21.73,800,62.50,0,4,2
747,GP Swann (ENG),2000-2013,79,48,12,500,34,13.88,553,90.41,0,0,3

In [3]:
df.set_index("Player")

,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0s
Player,,,,,,,,,,,,
SR Tendulkar (IND),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20
V Kohli (IND),2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76,18
KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,15
RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20
ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34
...,...,...,...,...,...,...,...,...,...,...,...,...
PR Reiffel (AUS),1992-1999,92,57,21,503,58,13.97,709,70.94,0,1,5
AR Nurse (WI),2016-2019,54,40,14,502,44,19.30,513,97.85,0,0,2
JE Emburey (ENG),1980-1993,61,45,10,501,34,14.31,664,75.45,0,0,3
Ghulam Shabber (UAE),2017-2019,23,23,0,500,90,21.73,800,62.50,0,4,2
GP Swann (ENG),2000-2013,79,48,12,500,34,13.88,553,90.41,0,0,3

In [4]:
df.shape

(748, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  748 non-null    object
 1   Span    748 non-null    object
 2   Mat     748 non-null    int64
 3   Inns    748 non-null    int64
 4   NO      748 non-null    int64
 5   Runs    748 non-null    int64
 6   HS      748 non-null    object
 7   Ave     748 non-null    float64
 8   BF      748 non-null    int64
 9   SR      748 non-null    float64
 10  100     748 non-null    int64
 11  50      748 non-null    int64
 12  0s      748 non-null    int64
dtypes: float64(2), int64(8), object(3)
memory usage: 76.1+ KB

# Overall missing value percentage in data

In [6]:
total_cells = df.size
total_missing = df.isnull().sum().sum()

overall_missing_percent = (total_missing / total_cells) * 100
print(f"Overall Missing Values: {overall_missing_percent:.2f}%")

Overall Missing Values: 0.00%

In [7]:
df.drop(columns = "0s",inplace = True)

In [8]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50'],
      dtype='object')

# Renaming the column for better understanding

In [9]:
df = df.rename(columns={
    "Player": "Player_Name",
    "Mat": "Matches",
    "Inns": "Innings",
    "Runs": "Total_Runs",
    "Ave": "Batting_Average",
    "SR": "Strike_Rate",
    "NO":"Not_Out",
    "HS":"Highest_Score",
    "BF":"Ball_Faced",
    "100":"100's",
    "50":"50's"
})
df.head()

,Player_Name,Span,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar (IND),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96
1,V Kohli (IND),2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68

# Adding column country to get country names

In [10]:
df[['Player_Names','Country']] = df['Player_Name'].str.rsplit(')',n=1,expand = True)

# Replacing parenthesis of country names

In [11]:
df[['Player_Names','Country']] = df['Player_Name'].str.rsplit('(',n=1,expand = True)

In [12]:
df["Country"] = df["Country"].str.replace(")","")

In [13]:
df.drop(columns = "Player_Name", inplace = True)

In [14]:
cols = ['Player_Names', 'Country'] + [c for c in df.columns if c not in ['Player_Names', 'Country']]
df = df[cols]
df.head()

,Player_Names,Country,Span,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,IND,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96
1,V Kohli,IND,2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Asia/ICC/SL,2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,AUS/ICC,1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Asia/SL,1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68

# Checking Duplicates

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isna().sum()

Player_Names       0
Country            0
Span               0
Matches            0
Innings            0
Not_Out            0
Total_Runs         0
Highest_Score      0
Batting_Average    0
Ball_Faced         0
Strike_Rate        0
100's              0
50's               0
dtype: int64

In [17]:
df.shape

(748, 13)

In [18]:
df.head(10)

,Player_Names,Country,Span,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,IND,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96
1,V Kohli,IND,2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Asia/ICC/SL,2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,AUS/ICC,1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Asia/SL,1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68
5,DPMD Jayawardene,Asia/SL,1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77
6,Inzamam-ul-Haq,Asia/PAK,1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83
7,JH Kallis,Afr/ICC/SA,1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86
8,RG Sharma,IND,2007-2025,279,271,37,11516,264,49.21,12402,92.85,33,61
9,SC Ganguly,Asia/IND,1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72

In [19]:
df["Country"].unique()

array(['IND', 'Asia/ICC/SL', 'AUS/ICC', 'Asia/SL', 'Asia/PAK',
       'Afr/ICC/SA', 'Asia/IND', 'Asia/ICC/IND', 'ICC/WI', 'SL', 'Afr/SA',
       'PAK', 'WI', 'NZ', 'BAN', 'SA', 'Asia/ICC/PAK', 'ICC/NZ', 'AUS',
       'ENG/IRE', 'ENG', 'ZIM', 'IRE', 'ENG/ICC', 'Afr/ZIM', 'AFG',
       'SCOT', 'Asia/BAN', 'Afr/KENYA', 'AUS/SA', 'USA', 'NAM', 'NED',
       'KENYA', 'PNG', 'NEP', 'CAN', 'UAE', 'OMA', 'AUS/NZ', 'HKG/NZ',
       'ENG/PNG', 'HKG', 'BER', 'USA/WI'], dtype=object)

In [20]:
df["Country"] = df["Country"].str.replace(r"(Asia|Afr|ICC)/", "", regex=True)
c_names = {
    "IND": "India",
    "AUS": "Australia",
    "SL": "Sri Lanka",
    "PAK": "Pakistan",
    "SA": "South Africa",
    "WI": "West Indies",
    "NZ": "New Zealand",
    "BAN": "Bangladesh",
    "ENG": "England",
    "IRE": "Ireland",
    "ZIM": "Zimbabwe",
    "AFG": "Afghanistan",
    "SCOT": "Scotland",
    "KENYA": "Kenya",
    "USA": "United States",
    "NAM": "Namibia",
    "NED": "Netherlands",
    "PNG": "Papua New Guinea",
    "CAN": "Canada",
    "UAE": "United Arab Emirates",
    "NEP": "Nepal",
    "OMA": "Oman",
    "AUS/ICC":"Australia",
    "ENG/ICC":"England",
    "AUS/SA":"Australia/South Africa",
    "AUS/NZ":"Australia/New Zealand",
    'ENG/IRE':'England/Ireland'
}
df["Country"] = df["Country"].replace(c_names)

In [21]:
df.head(10)

,Player_Names,Country,Span,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,India,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96
1,V Kohli,India,2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Sri Lanka,2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,Australia,1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Sri Lanka,1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68
5,DPMD Jayawardene,Sri Lanka,1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77
6,Inzamam-ul-Haq,Pakistan,1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83
7,JH Kallis,South Africa,1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86
8,RG Sharma,India,2007-2025,279,271,37,11516,264,49.21,12402,92.85,33,61
9,SC Ganguly,India,1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72

In [22]:
df.head(10)

,Player_Names,Country,Span,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,India,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96
1,V Kohli,India,2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Sri Lanka,2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,Australia,1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Sri Lanka,1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68
5,DPMD Jayawardene,Sri Lanka,1998-2015,448,418,39,12650,144,33.37,16020,78.96,19,77
6,Inzamam-ul-Haq,Pakistan,1991-2007,378,350,53,11739,137*,39.52,15812,74.24,10,83
7,JH Kallis,South Africa,1996-2014,328,314,53,11579,139,44.36,15885,72.89,17,86
8,RG Sharma,India,2007-2025,279,271,37,11516,264,49.21,12402,92.85,33,61
9,SC Ganguly,India,1992-2007,311,300,23,11363,183,41.02,15416,73.70,22,72

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player_Names     748 non-null    object
 1   Country          748 non-null    object
 2   Span             748 non-null    object
 3   Matches          748 non-null    int64
 4   Innings          748 non-null    int64
 5   Not_Out          748 non-null    int64
 6   Total_Runs       748 non-null    int64
 7   Highest_Score    748 non-null    object
 8   Batting_Average  748 non-null    float64
 9   Ball_Faced       748 non-null    int64
 10  Strike_Rate      748 non-null    float64
 11  100's            748 non-null    int64
 12  50's             748 non-null    int64
dtypes: float64(2), int64(7), object(4)
memory usage: 76.1+ KB

# Covreting span into two columns

In [24]:
df[['Start_Year', 'End_Year']] = df['Span'].str.split('-', expand=True)

In [25]:
df

,Player_Names,Country,Span,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's,Start_Year,End_Year
0,SR Tendulkar,India,1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,1989,2012
1,V Kohli,India,2008-2025,308,296,47,14557,183,58.46,15543,93.65,53,76,2008,2025
2,KC Sangakkara,Sri Lanka,2000-2015,404,380,41,14234,169,41.98,18048,78.86,25,93,2000,2015
3,RT Ponting,Australia,1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,1995,2012
4,ST Jayasuriya,Sri Lanka,1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,1989,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,PR Reiffel,Australia,1992-1999,92,57,21,503,58,13.97,709,70.94,0,1,1992,1999
744,AR Nurse,West Indies,2016-2019,54,40,14,502,44,19.30,513,97.85,0,0,2016,2019
745,JE Emburey,England,1980-1993,61,45,10,501,34,14.31,664,75.45,0,0,1980,1993
746,Ghulam Shabber,United Arab Emirates,2017-2019,23,23,0,500,90,21.73,800,62.50,0,4,2017,2019
747,GP Swann,England,2000-2013,79,48,12,500,34,13.88,553,90.41,0,0,2000,2013

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player_Names     748 non-null    object
 1   Country          748 non-null    object
 2   Span             748 non-null    object
 3   Matches          748 non-null    int64
 4   Innings          748 non-null    int64
 5   Not_Out          748 non-null    int64
 6   Total_Runs       748 non-null    int64
 7   Highest_Score    748 non-null    object
 8   Batting_Average  748 non-null    float64
 9   Ball_Faced       748 non-null    int64
 10  Strike_Rate      748 non-null    float64
 11  100's            748 non-null    int64
 12  50's             748 non-null    int64
 13  Start_Year       748 non-null    object
 14  End_Year         748 non-null    object
dtypes: float64(2), int64(7), object(6)
memory usage: 87.8+ KB

# Replacing *

In [27]:
df['Highest_Score'] = df['Highest_Score'].astype(str).str.replace('*', '', regex=False)
df['Highest_Score'] = pd.to_numeric(df['Highest_Score'])

# Making new order

In [28]:
new_order = [
    'Player_Names', 'Country', 'Start_Year', 'End_Year', 
    'Matches', 'Innings', 'Not_Out', 'Total_Runs', 
    'Highest_Score', 'Batting_Average', 'Ball_Faced', 
    'Strike_Rate', "100's", "50's"
]

df = df[[col for col in new_order if col in df.columns]]

In [29]:
df.head()

,Player_Names,Country,Start_Year,End_Year,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,India,1989,2012,463,452,41,18426,200,44.83,21368,86.23,49,96
1,V Kohli,India,2008,2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Sri Lanka,2000,2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,Australia,1995,2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Sri Lanka,1989,2011,445,433,18,13430,189,32.36,14725,91.20,28,68

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player_Names     748 non-null    object
 1   Country          748 non-null    object
 2   Start_Year       748 non-null    object
 3   End_Year         748 non-null    object
 4   Matches          748 non-null    int64
 5   Innings          748 non-null    int64
 6   Not_Out          748 non-null    int64
 7   Total_Runs       748 non-null    int64
 8   Highest_Score    748 non-null    int64
 9   Batting_Average  748 non-null    float64
 10  Ball_Faced       748 non-null    int64
 11  Strike_Rate      748 non-null    float64
 12  100's            748 non-null    int64
 13  50's             748 non-null    int64
dtypes: float64(2), int64(8), object(4)
memory usage: 81.9+ KB

In [31]:
df['Player_Names'].str.upper()

0        SR TENDULKAR
1             V KOHLI
2       KC SANGAKKARA
3          RT PONTING
4       ST JAYASURIYA
            ...
743        PR REIFFEL
744          AR NURSE
745        JE EMBUREY
746    GHULAM SHABBER
747          GP SWANN
Name: Player_Names, Length: 748, dtype: object

In [32]:
df[["Start_Year","End_Year"]] = df[["Start_Year","End_Year"]].astype(object)

In [33]:
df["Player_Names"].nunique()

747

In [34]:
df

,Player_Names,Country,Start_Year,End_Year,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,India,1989,2012,463,452,41,18426,200,44.83,21368,86.23,49,96
1,V Kohli,India,2008,2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Sri Lanka,2000,2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,Australia,1995,2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Sri Lanka,1989,2011,445,433,18,13430,189,32.36,14725,91.20,28,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,PR Reiffel,Australia,1992,1999,92,57,21,503,58,13.97,709,70.94,0,1
744,AR Nurse,West Indies,2016,2019,54,40,14,502,44,19.30,513,97.85,0,0
745,JE Emburey,England,1980,1993,61,45,10,501,34,14.31,664,75.45,0,0
746,Ghulam Shabber,United Arab Emirates,2017,2019,23,23,0,500,90,21.73,800,62.50,0,4
747,GP Swann,England,2000,2013,79,48,12,500,34,13.88,553,90.41,0,0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player_Names     748 non-null    object
 1   Country          748 non-null    object
 2   Start_Year       748 non-null    object
 3   End_Year         748 non-null    object
 4   Matches          748 non-null    int64
 5   Innings          748 non-null    int64
 6   Not_Out          748 non-null    int64
 7   Total_Runs       748 non-null    int64
 8   Highest_Score    748 non-null    int64
 9   Batting_Average  748 non-null    float64
 10  Ball_Faced       748 non-null    int64
 11  Strike_Rate      748 non-null    float64
 12  100's            748 non-null    int64
 13  50's             748 non-null    int64
dtypes: float64(2), int64(8), object(4)
memory usage: 81.9+ KB

# Some rows removing for better visiualization

In [36]:
df['Player_Names'].unique()

array(['SR Tendulkar ', 'V Kohli ', 'KC Sangakkara ', 'RT Ponting ',
       'ST Jayasuriya ', 'DPMD Jayawardene ', 'Inzamam-ul-Haq ',
       'JH Kallis ', 'RG Sharma ', 'SC Ganguly ', 'R Dravid ',
       'MS Dhoni ', 'CH Gayle ', 'BC Lara ', 'TM Dilshan ',
       'Mohammad Yousuf ', 'AC Gilchrist ', 'AB de Villiers ',
       'M Azharuddin ', 'PA de Silva ', 'Saeed Anwar ', 'S Chanderpaul ',
       'Yuvraj Singh ', 'DL Haynes ', 'LRPL Taylor ', 'MS Atapattu ',
       'Tamim Iqbal ', 'V Sehwag ', 'HM Amla ', 'HH Gibbs ',
       'Shahid Afridi ', 'SP Fleming ', 'MJ Clarke ', 'Mushfiqur Rahim ',
       'EJG Morgan ', 'Shakib Al Hasan ', 'SR Waugh ', 'Shoaib Malik ',
       'A Ranatunga ', 'MJ Guptill ', 'JE Root ', 'KS Williamson ',
       'Younis Khan ', 'Saleem Malik ', 'Q de Kock ', 'NJ Astle ',
       'GC Smith ', 'WU Tharanga ', 'DA Warner ', 'MG Bevan ',
       'G Kirsten ', 'S Dhawan ', 'A Flower ', 'IVA Richards ',
       'BRM Taylor ', 'Mohammad Hafeez ', 'GW Flower ', 'Ijaz Ahmed ',
       'AR Border ', 'Babar Azam ', 'RB Richardson ', 'ML Hayden ',
       'SD Hope ', 'BB McCullum ', 'DM Jones ', 'PR Stirling ',
       'DC Boon ', 'JN Rhodes ', 'AD Mathews ', 'Ramiz Raja ',
       'RR Sarwan ', 'SPD Smith ', 'CL Hooper ', 'SR Watson ',
       'Mahmudullah ', 'H Masakadza ', 'SK Raina ', 'MN Samuels ',
       'WJ Cronje ', 'F du Plessis ', 'JC Buttler ', 'MEK Hussey ',
       'IR Bell ', 'AJ Finch ', 'A Jadeja ', 'DR Martyn ', 'G Gambhir ',
       'SC Williams ', 'ADR Campbell ', 'RS Mahanama ', 'CG Greenidge ',
       'Misbah-ul-Haq ', 'JP Duminy ', 'PD Collingwood ', 'A Symonds ',
       'Abdul Razzaq ', 'CL Cairns ', 'Aamer Sohail ', 'BKG Mendis ',
       'CD McMillan ', 'MD Crowe ', 'MV Boucher ', 'AJ Stewart ',
       'DA Miller ', 'SB Styris ', 'Sikandar Raza ', 'TWM Latham ',
       'KP Pietersen ', 'NS Sidhu ', 'CZ Harris ', 'GR Marsh ',
       'WTS Porterfield ', 'E Chigumbura ', 'ME Trescothick ',
       'GA Gooch ', 'JJ Roy ', 'AJ Strauss ', 'K Srikkanth ',
       'Rahmat Shah ', 'AJ Lamb ', 'GJ Maxwell ', 'RP Arnold ',
       'AP Gurusinha ', 'JG Wright ', 'JM Bairstow ', 'Fakhar Zaman ',
       'DJ Cullinan ', 'LD Chandimal ', 'GA Hick ', 'HP Tillakaratne ',
       'N Kapil Dev ', 'Mohammad Nabi ', 'Wasim Akram ',
       'RS Kaluwitharana ', 'Imran Khan ', 'PV Simmons ', 'NV Knight ',
       "KJ O'Brien ", 'RD Berrington ', 'CR Ervine ', 'L Klusener ',
       'SM Pollock ', 'MA Taylor ', 'DB Vengsarkar ',
       'Mohammad Ashraful ', 'BA Stokes ', 'SO Tikolo ', 'HH Dippenaar ',
       'A Flintoff ', 'T Taibu ', 'KC Wessels ', 'AC Parore ',
       'Moin Khan ', 'A Balbirnie ', 'MDKJ Perera ', 'Kamran Akmal ',
       'KL Rahul ', 'AN Cook ', 'HDRL Thirimanne ', 'Umar Akmal ',
       'KJ Coetzer ', 'DI Gower ', 'Imam-ul-Haq ', 'KR Rutherford ',
       'BJ Haddin ', 'DM Bravo ', 'RJ Shastri ', 'MR Marsh ',
       'SM Gavaskar ', 'DS Lehmann ', 'GJ Bailey ', 'CS MacLeod ',
       'TM Head ', 'V Sibanda ', 'DJ Bravo ', 'AM Rahane ', 'HH Streak ',
       'Mohammad Rizwan ', 'SS Iyer ', 'WW Hinds ', 'RA Jadeja ',
       'P Nissanka ', 'IJL Trott ', 'Shubman Gill ', 'AL Logie ',
       'AH Jones ', 'SE Marsh ', 'M Kaif ', 'SV Carlisle ',
       'Mohammad Shahzad ', 'Salman Butt ', 'RG Twose ', 'AK Markram ',
       'KA Pollard ', 'GJ Whittall ', 'RS Bopara ', 'KIC Asalanka ',
       'HE van der Dussen ', 'Mudassar Nazar ', 'HG Munsey ', 'EC Joyce ',
       'Ahmed Shehzad ', "NJ O'Brien ", 'Zaheer Abbas ', 'Litton Das ',
       'AC Hudson ', 'VG Kambli ', 'CJ Chibhabha ',
       'Hashmatullah Shahidi ', 'Imrul Kayes ', 'JDP Oram ',
       'Asghar Afghan ', 'TM Odoyo ', 'AD Hales ', 'RA Smith ',
       'L Vincent ', 'GP Thorpe ', 'MM Ali ', 'VVS Laxman ',
       'DJ Mitchell ', 'NLTC Perera ', 'Soumya Sarkar ', 'RR Singh ',
       'N Hussain ', 'GS Chappell ', 'Sarfaraz Ahmed ', 'MD Patel ',
       'SL Campbell ', 'E Lewis ', 'DL Vettori ', 'AT Carey ',
       'JO Holder ', 'S Matsikenyeri ', 'GM Wood ', 'MH Cross ',
       'MJ Greatbatch ', 'JC Adams ', 'Shahriar Nafees ', 'D Ramdin ',
       'HM Nicholls ', 'MG Erasmus ', 'Habibul Bashar ', "MP O'Dowd ",
       'H Klaasen ', 'IT Botham ', 'SA Edwards ', 'MW Gatting ',
       'NH Fairbrother ', 'RL Powell ', 'CL White ', 'GC Wilson ',
       'Najibullah Zadran ', 'CO Obuya ', 'T Bavuma ', 'Yasir Hameed ',
       'WPUJC Vaas ', 'KO Otieno ', 'A Vala ', 'RK Paudel ',
       'SV Manjrekar ', 'HT Tector ', 'N Pooran ', 'MP Vaughan ',
       'CH Lloyd ', 'GD Elliott ', 'KJ Hughes ', 'A Bagai ',
       'LMP Simmons ', 'Aftab Ahmed ', 'PJL Dujon ', 'M Amarnath ',
       'KLT Arthurton ', 'HH Pandya ', 'Imran Nazir ',
       'Rahmanullah Gurbaz ', 'Mohsin Khan ', 'JV Coney ',
       'M Labuschagne ', 'DJG Sammy ', 'Ibrahim Zadran ', 'MS Wade ',
       'V Aravind ', 'DM de Silva ', 'RD Jacobs ', 'M Prabhakar ',
       'Azhar Ali ', 'OA Shah ', 'MW Goodwin ', 'Khaled Mashud ',
       'BA Edgar ', 'Samiullah Shinwari ', 'DJ Hussey ', 'MA Atherton ',
       'Mehidy Hasan Miraz ', 'Mashrafe Mortaza ', 'IA Healy ',
       'KD Karthik ', 'Sir RJ Hadlee ', 'Haris Sohail ', 'Imran Farhat ',
       'CB Wishart ', 'Rashid Latif ', 'DA Gunawardene ',
       'Najmul Hossain Shanto ', 'Jatinder Singh ', 'Muhammad Waseem ',
       'AT Rayudu ', 'WA Young ', 'ND McKenzie ', 'NC Johnson ',
       'Aasif Sheikh ', 'BA Young ', 'Aaron Jones ', 'UDU Chandana ',
       'CK Kapugedera ', 'DP Conway ', 'N Dickwella ', 'MD Gunathilaka ',
       'GM Turner ', 'KU Carty ', 'WIA Fernando ', 'LPC Silva ',
       'MJ Santner ', 'Saleem Elahi ', 'RL Dias ', 'DR Smith ',
       'UT Khawaja ', 'MA Leask ', 'IK Pathan ', 'SO Hetmyer ',
       'RN ten Doeschate ', 'J Charles ', 'DL Houghton ', 'BA King ',
       'LRD Mendis ', 'CR Woakes ', 'Azhar Mahmood ', 'RS Morton ',
       'JJ Crowe ', 'JM Kemp ', 'RD Shah ', 'Rohan Mustafa ', 'MA Ouma ',
       'JDS Neesham ', 'MP Stoinis ', 'GH Dockrell ', 'S Samarawickrama ',
       'K Bhurtel ', 'HJH Marshall ', 'DJ Malan ', 'DD Ebrahim ',
       'R Ravindra ', 'Nasir Jamshed ', 'HA Gomes ', 'N Boje ',
       'MO Odumbe ', 'P Utseya ', 'Aarif Sheikh ', 'L Ronchi ',
       'Rashid Khan ', 'KM Jadhav ', 'GP Howarth ', 'Agha Salman ',
       'TP Ura ', 'JD Ryder ', 'BC Broad ', 'DO Obuya ', 'Anamul Haque ',
       'W Barresi ', 'Asad Shafiq ', 'PG Fulton ', 'Sabbir Rahman ',
       'Gulbadin Naib ', 'KMDN Kulasekara ', 'JR Hopes ', 'SM Katich ',
       'TLW Cooper ', 'M van Lingen ', 'FDM Karunaratne ', 'Javed Omar ',
       'Raqibul Hasan ', 'AA Obanda ', 'MS Sinclair ', 'Vikramjit Singh ',
       'MD Shanaka ', 'PN Kirsten ', 'MJ Prior ', 'Nasir Hossain ',
       'Zeeshan Maqsood ', 'NR Mongia ', 'C Munro ', 'Asif Khan ',
       'JEC Franklin ', 'AB Agarkar ', 'Shoaib Mohammad ', 'Basit Ali ',
       'SR Taylor ', 'Towhid Hridoy ', 'MN Waller ', 'SR Mukkamalla ',
       "SP O'Donnell ", 'DS Airee ', 'BFW de Leede ', 'RR Rossouw ',
       'BM Duckett ', 'Harbhajan Singh ', 'SG Law ', 'Alok Kapali ',
       'Aqib Ilyas ', 'GM Hamilton ', 'D Mongia ', 'RW Marsh ',
       'HDPK Dharmasena ', 'Shaiman Anwar ', 'Noor Ali Zadran ',
       'TM Moody ', 'B McMullen ', 'Junaid Siddique ',
       'Mohammad Rafique ', 'RW Chakabva ', 'B Lee ', 'JA Rudolph ',
       'HC Brook ', 'RL Chase ', 'Nawroz Mangal ', 'CJA Amini ',
       'T Mishra ', 'PW Hasaranga ', 'PL Mommsen ', 'C Campher ',
       'JN Loftie-Eaton ', 'MF Maharoof ', 'GD Phillips ', 'CJ Anderson ',
       'HS Modi ', 'ES Szwarczynski ', 'VS Solanki ', 'B Zuiderent ',
       'Azmatullah Omarzai ', 'PA Strang ', 'S Bau ', 'G Boycott ',
       'F Behardien ', 'Ayaan Khan ', 'JJ Smit ', 'NL McCullum ',
       'Asif Mujtaba ', 'DW Randall ', 'DS Smith ', 'JK Kamande ',
       'IDS Smith ', 'C Kieswetter ', 'LJ Tucker ', 'Basil Hameed ',
       'Javed Ahmadi ', 'KH Prajapati ', 'KD Mills ', 'JM How ',
       'AD Russell ', 'JP Faulkner ', 'DSBP Kuruppu ', 'AG Prince ',
       'SK Warne ', 'Milind Kumar ', 'Muhammad Usman ', 'SM Patil ',
       'KOA Powell ', 'Rajin Saleh ', 'PW Borren ', 'NFI McCallum ',
       'Khaled Mahmud ', 'PD Salt ', 'BL Cairns ', 'MJ Slater ',
       'Imad Wasim ', 'G Singh ', 'B Sharki ', 'MJ Horne ', 'R Powell ',
       'Akram Khan ', 'Naeem Islam ', 'RR Hendricks ', 'DF Watts ',
       'AU Rashid ', 'Waqar Younis ', 'Fawad Alam ', 'SA Thomson ',
       'JF Mooney ', 'Pargat Singh ', 'GM Ritchie ', 'JN Malan ',
       'RR Watson ', 'MD Marshall ', 'SF Mire ', 'MG Johnson ',
       'RS Madugalle ', 'CP Rizwan ', 'Chirag Suri ', 'JN Frylinck ',
       'NT Broom ', 'ZE Green ', 'RP Burl ', 'A Kumble ',
       'Rameez Shahzad ', 'CM Spearman ', 'RV Uthappa ', 'Ishan Kishan ',
       'MS Chapman ', 'LS Livingstone ', 'L Siaka ', 'AN Kervezee ',
       'AR McBrine ', 'S Dhaniram ', 'MG Bracewell ', 'J Liyanage ',
       'AJ Hall ', 'SJ Modani ', 'AT Nidamanuru ', 'TD Paine ',
       'JWA Taylor ', 'AL Phehlukwayo ', 'J Srinath ', 'Yashpal Sharma ',
       'G Malla ', 'TT Bresnan ', 'RR Pant ', 'SHT Kandamby ',
       'AC Voges ', 'DJ Richardson ', 'MA Vermeulen ', 'HK Badani ',
       'GO Jones ', 'Mohammad Nadeem ', 'TT Samaraweera ', 'SB Smith ',
       'DL Amiss ', 'AR Patel ', 'RA Harper ', 'Shadab Khan ',
       'WB Phillips ', 'CWJ Athey ', 'RS Kalpage ', 'MAR Samarasekera ',
       'D Ganga ', 'CA Ingram ', 'Shoaib Khan ', 'SSJ Brooks ',
       'BM McMillan ', 'N Vanua ', 'CK Coventry ', 'Anshuman Rath ',
       'PJ Moor ', 'DW Hookes ', 'PJ Hughes ', 'AI Kallicharran ',
       'JR Ratnayeke ', 'GN Yallop ', 'AC Waller ', 'Kushal Malla ',
       'Sharjeel Khan ', 'YK Pathan ', 'JM Davison ', 'Shayan Jahangir ',
       'Aminul Islam ', 'Z Khan ', 'GB Hogg ', 'H Thaker ', 'Majid Khan ',
       'S Wettimuny ', 'Babar Hayat ', 'R Lamba ', 'IH Romaine ',
       'C Green ', 'W Madhevere ', 'JA Morkel ', 'Wasim Raja ',
       'Sohaib Maqsood ', 'Abdur Razzak ', 'Sompal Kami ', 'AR White ',
       'SA Yadav ', 'Saleem Yousuf ', 'JP Inglis ', 'CN Evans ',
       'Rizwan Cheema ', 'KWR Fletcher ', 'J Dyson ', 'Saim Ayub ',
       'CA Soper ', 'AR Cusack ', 'AG Cremer ', 'G Fowler ',
       'DT Johnston ', 'SE Rutherford ', 'C de Grandhomme ',
       'Manzoor Elahi ', 'AM Samad ', 'TG Southee ', 'Wahab Riaz ',
       'Abdullah Shafique ', 'PA Patel ', 'MW Machan ', 'MRJ Watt ',
       'CJ Nevin ', 'K Doriga ', 'Gulsan Jha ', 'CJ Tavare ',
       'MA Ealham ', 'IJ Harvey ', 'Mohammad Mithun ', 'Saqlain Mushtaq ',
       'R Ashwin ', 'LJ Wright ', 'MP Breetzke ', 'T de Zorzi ',
       'J Mubarak ', 'SW Billings ', 'PA Wallace ', 'SM Ervine ',
       'PL Symcox ', 'PAJ DeFreitas ', 'N Deonarine ', 'JR Murray ',
       'Nizakat Khan ', 'M Muralidaran ', 'IM Chappell ', 'DA Marillier ',
       'UC Hathurusingha ', 'Afif Hossain ', 'AC Botha ', 'CJ Ferguson ',
       'DJ Willey ', 'KR Mayers ', 'SK Patel ', 'LE Plunkett ',
       'S Ramesh ', 'Qasim Umar ', 'Abdul Qadir ', 'DL Hemp ',
       'CEL Ambrose ', 'SM Curran ', 'BMAJ Mendis ', 'Mosaddek Hossain ',
       'JF Reid ', 'DLS van Bunge ', 'PSP Handscomb ', 'JN Mohammed ',
       'RMH Binny ', 'Karan KC ', 'GR Larsen ', 'AM Blignaut ',
       'Khawar Ali ', 'NR Kirton ', 'DJ Nash ', 'DN Patel ', 'WG Jacks ',
       'RR Patel ', 'GRJ Matthews ', 'R Mutumbami ', 'WV Raman ',
       'GJ Rennie ', 'JM Vince ', 'Iftikhar Ahmed ', 'SFAF Bacchus ',
       'RJ Ratnayake ', 'J Botha ', 'D Gough ', 'SM Sharif ',
       'AJ Hollioake ', 'RIC Holder ', 'RT Robinson ', 'XM Marshall ',
       'Aayan Afzal Khan ', 'BM Laird ', 'Mansoor Akhtar ', 'Simi Singh ',
       'W Larkins ', 'LOB Cann ', 'RJ Nicol ', 'SB Joshi ', 'JP Kotze ',
       'Sandeep Goud ', 'RT Latham ', 'MA Starc ', 'FH Allen ',
       'Khurram Khan ', 'L Louwrens ', 'JL Carter ', 'DAS Gunaratne ',
       'BJ Hodge ', 'MJR Rindel ', 'WD Parnell ', 'Tushar Imran ',
       'CD Wallace ', 'BJ Watling ', 'C White ', 'SL Malinga ', 'RM Haq ',
       'MK Pandey ', 'KS More ', 'CR Brathwaite ', 'Tanzid Hasan ',
       'Mominul Haque ', 'Aamer Malik ', 'RJ Peterson ', 'M Jansen ',
       'B Kumar ', 'GS Blewett ', 'TJ Friend ', 'T Duffin ',
       'Mohammad Wasim ', 'AP Kuiper ', 'Mohammad Nawaz (3) ',
       'P Willey ', 'PJ Cummins ', 'MC Snedden ', 'K Verreynne ',
       'Athar Ali Khan ', 'R Trumpelmann ', 'IS Billcliff ', 'SCJ Broad ',
       'NN Odhiambo ', 'PHKD Mendis ', 'SJ Myburgh ', 'Naved-ul-Hasan ',
       'Amjad Ali ', 'LK Germon ', 'JG Bethell ', 'Mudassar Bukhari ',
       'TAM Siriwardana ', 'KM Dabengwa ', 'PK Amre ', 'Dawlat Zadran ',
       'KD Walters ', 'JG Bracewell ', 'DP Viljoen ', 'JM Brearley ',
       'SV Samson ', 'AO Suji ', 'CN Ackermann ', 'AN Petersen ',
       'Taufeeq Umar ', 'PR Reiffel ', 'AR Nurse ', 'JE Emburey ',
       'Ghulam Shabber ', 'GP Swann '], dtype=object)

In [37]:
df = df[df["Country"] != "England/Ireland"]
df = df[df["Country"] != "Australia/South Africa"]
df = df[df["Country"] != "Australia/New Zealand"]
df

,Player_Names,Country,Start_Year,End_Year,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,India,1989,2012,463,452,41,18426,200,44.83,21368,86.23,49,96
1,V Kohli,India,2008,2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Sri Lanka,2000,2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,Australia,1995,2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Sri Lanka,1989,2011,445,433,18,13430,189,32.36,14725,91.20,28,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,PR Reiffel,Australia,1992,1999,92,57,21,503,58,13.97,709,70.94,0,1
744,AR Nurse,West Indies,2016,2019,54,40,14,502,44,19.30,513,97.85,0,0
745,JE Emburey,England,1980,1993,61,45,10,501,34,14.31,664,75.45,0,0
746,Ghulam Shabber,United Arab Emirates,2017,2019,23,23,0,500,90,21.73,800,62.50,0,4
747,GP Swann,England,2000,2013,79,48,12,500,34,13.88,553,90.41,0,0

In [38]:
df['Country'].unique()

array(['India', 'Sri Lanka', 'Australia', 'Pakistan', 'South Africa',
       'West Indies', 'New Zealand', 'Bangladesh', 'England', 'Zimbabwe',
       'Ireland', 'Afghanistan', 'Scotland', 'Kenya', 'United States',
       'Namibia', 'Netherlands', 'Papua New Guinea', 'Nepal', 'Canada',
       'United Arab Emirates', 'Oman', 'HKG/NZ', 'ENG/PNG', 'HKG', 'BER',
       'USA/WI'], dtype=object)

In [39]:
df.drop(df[df['Player_Names'] == 'SC Williams'].index, inplace=True)

# Converting DataFrame into CSV file

In [40]:
df.to_csv("Player_stats_Clean_Dataset.csv",index = False)

In [41]:
df

,Player_Names,Country,Start_Year,End_Year,Matches,Innings,Not_Out,Total_Runs,Highest_Score,Batting_Average,Ball_Faced,Strike_Rate,100's,50's
0,SR Tendulkar,India,1989,2012,463,452,41,18426,200,44.83,21368,86.23,49,96
1,V Kohli,India,2008,2025,308,296,47,14557,183,58.46,15543,93.65,53,76
2,KC Sangakkara,Sri Lanka,2000,2015,404,380,41,14234,169,41.98,18048,78.86,25,93
3,RT Ponting,Australia,1995,2012,375,365,39,13704,164,42.03,17046,80.39,30,82
4,ST Jayasuriya,Sri Lanka,1989,2011,445,433,18,13430,189,32.36,14725,91.20,28,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,PR Reiffel,Australia,1992,1999,92,57,21,503,58,13.97,709,70.94,0,1
744,AR Nurse,West Indies,2016,2019,54,40,14,502,44,19.30,513,97.85,0,0
745,JE Emburey,England,1980,1993,61,45,10,501,34,14.31,664,75.45,0,0
746,Ghulam Shabber,United Arab Emirates,2017,2019,23,23,0,500,90,21.73,800,62.50,0,4
747,GP Swann,England,2000,2013,79,48,12,500,34,13.88,553,90.41,0,0